// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("Feliz.Recoil.Bridge")>]
[<assembly: AssemblyProductAttribute("Feliz.Recoil")>]
[<assembly: AssemblyDescriptionAttribute("Fable bindings in Feliz style for Facebook's experimental state management library recoil.")>]
[<assembly: AssemblyVersionAttribute("0.17.2")>]
[<assembly: AssemblyFileVersionAttribute("0.17.2")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
[<assembly: InternalsVisibleToAttribute("Feliz.Recoil.Bridge.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Feliz.Recoil.Bridge"
    let [<Literal>] AssemblyProduct = "Feliz.Recoil"
    let [<Literal>] AssemblyDescription = "Fable bindings in Feliz style for Facebook's experimental state management library recoil."
    let [<Literal>] AssemblyVersion = "0.17.2"
    let [<Literal>] AssemblyFileVersion = "0.17.2"
    let [<Literal>] AssemblyConfiguration = "Release"
    let [<Literal>] InternalsVisibleTo = "Feliz.Recoil.Bridge.Tests"
